# Generated by Django 4.1.1 on 2022-10-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publications_las_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='email',
            field=models.EmailField(default='email@mail.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='publications',
            name='patronim',
            field=models.CharField(default='Василич', max_length=50),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publications')),
            ],
        ),
    ]
